name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install SQLC
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - name: Install SQLC
        run: go install go.uber.org/mock/mockgen@latest
      - name: Mod Download
        run: go mod download
      - name: SQLC Generate
        run: sqlc generate
      - name: Generate
        run: go generate ./...
      - name: Build
        run: go build -v cmd/main.go
      - name: Test
        run: go test -v ./...