name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install SQLC
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - name: Generate
        run: go mod download && go generate ./...
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...